version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  validate:
    docker:
      - image: cimg/base:stable
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./reports/
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18'
      - node/install-packages:
          cache-path: ./node_modules/
          pkg-manager: yarn
      - run:
          name: Lint, Build, and Test
          command: |
            yarn lint
            yarn build
            yarn test --ci
      - run:
          name: Report Test Coverage
          environment:
            COVERALLS_SERVICE_NAME: 'circleci'
          command: |
            export COVERALLS_GIT_BRANCH=$CIRCLE_BRANCH
            export COVERALLS_SERVICE_JOB_ID=$CIRCLE_BUILD_NUM
            npx coveralls < coverage/lcov.info
      - store_test_results:
          path: ./reports/
      - store_artifacts:
          path: ./logs/
      - persist_to_workspace:
          root: ./
          paths:
            - ./

workflows:
  test-only:
    jobs:
      - validate
